### ISSUE TITLE
Sharing iP code quality feedback [for @Sheeepen]

### ISSUE THREAD

**Issue by nus-se-script** [Sheeepen/ip#6]
@Sheeepen We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/Duke.java` lines `48-51`](https://github.com/Sheeepen/ip/blob/a905bb0219ebee3a50d274a92f7c6aec6bfda4f9/src/main/java/Duke.java#L48..L51):

```java

    /**
     * You should have your own function to generate a response to user input.
     * Replace this stub with your completed method.
     */

```

Example from [`src/main/java/commands/Command.java` lines `11-15`](https://github.com/Sheeepen/ip/blob/a905bb0219ebee3a50d274a92f7c6aec6bfda4f9/src/main/java/commands/Command.java#L11..L15):

```java

    /**
     * Execute the set of instructions based on the Command subclass
     *
     * @param tasks A TaskList object containing all tasks in the task list.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message

possible problems in commit [`b6452c2`](https://github.com/Sheeepen/ip/commit/b6452c2c6bb23221496b9c57ac02370a396a009c):

```

Merge branch 'branch-Level-10'
merge branch level 10


```

* No blank line between subject and body
            

possible problems in commit [`b5899cd`](https://github.com/Sheeepen/ip/commit/b5899cd6b95b0a16c226a8b5d8d2d1b4845e9837):

```

Merge branch 'branch-A-CheckStyle'
merge checkstyle branch


```

* No blank line between subject and body
            

possible problems in commit [`6f93b7c`](https://github.com/Sheeepen/ip/commit/6f93b7cfbd132c05ffca72ef838c3509b9e89f2b):

```

Merge branch 'branch-A-JavaDoc'
merge JavaDocs branch


```

* No blank line between subject and body
             

**Suggestion:** Follow the given [conventions for Git commit messages](https://se-education.org/guides/conventions/git.html) for _future_ commits (no need to modify past commit messages).

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

----

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by Sheeepen** [comment]
Header comments adjusted, future commit messages will be corrected accordingly.
